steps:

- id: Docker build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}', '.']
  
- id: Container image push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}']

- id: Cloud run deploy
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image'
  - '${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}'
  - '--port'
  - '8080'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  # - '--service-account'
  # - '${_SERVICE_ACCOUNT}'
  - '--max-instances'
  - '5'
  - '--timeout'
  - '60'
  # - '--set-secrets'
  # - 'SECRET_KEY=${_SECRET_ID}:latest'   
  - '--set-env-vars'
  - 'api_key=AIzaSyBGB1mXdikSsTXoiIL8-VdhHpclMZ5yJuE'
  

  
images:
- ${_REPO_REGION}/${_PROJ_ID}/${_REPO_NAME}/${_SERVICE_NAME}

substitutions:
  _REPO_REGION: asia-docker.pkg.dev
  _REPO_NAME: dev-repo
  _SERVICE_NAME: gemini-qna-api
  _REGION: asia-southeast1
  _PROJ_ID: nabhrnd
  # _SERVICE_ACCOUNT: 
